image:
  file: .gitpod.Dockerfile

tasks:
  - init: quarto check    &&
      quarto --version    &&
      R --version         &&
      tex --version       &&
      inkscape --version  &&
      gs --version 
    
ports:
  - port: 8080
    visibility: public
    onOpen: open-browser

