image:
  file: .gitpod.Dockerfile
  
ports:
- port: 8080  
  visibility: public
  onOpen: open-preview

tasks:
  - init: quarto check             &&
      quarto install chromium      &&     
      quarto install tinytex       &&
      quarto render --to html      &&
      mv _book public              &&
      apachectl start 
