version: 1.0

image: Dockerfile  # Reference the correct Dockerfile

ports:
  - name: web
    port: 8080
    visibility: public
    onOpen: open-preview

tasks:
  - name: Setup Environment
    init: |
      quarto check &&
      quarto install tinytex &&
      quarto render &&
      mv _book public &&
      apachectl start
    command: quarto serve --port 8080
